### ISSUE TITLE
Unnecessary dependency on docutils 

### ISSUE THREAD

**Issue by CarstenLeue** [IBM/ibm-cos-sdk-python-core#11]
The SDK declares a dependency on `docutils` here https://github.com/IBM/ibm-cos-sdk-python-core/blob/master/setup.py#L7

docutils is released under GPL which is much harder to clear for an IBM consumer than the Apache license of the SDK itself. 
Briefly looking at the code it appears as if the dependency on `docutils` were only required during the build of the documentation but not at runtime. 

I suggest to remove the runtime dependency on `docutils` so consumers have a shorter dependency list without any GPL licensed dependency.

**Comment by IBM-Justin** [comment]
We appreciate your feedback to remove `docutils` from [setup.py]( https://github.com/IBM/ibm-cos-sdk-python-core/blob/master/setup.py#L7). 

Thank you for taking the time out to make this suggestion @CarstenLeue.

We will update this ticket when we complete our evaluation.

**Comment by IBM-Justin** [comment]
Hi @CarstenLeue,

We have scheduled the `docutils` dependency removal to be included in our Q4 release.

**Comment by IBMeric** [comment]
This has been resolved in the 2.9.0 release. Please verify and close this ticket.
