### ISSUE TITLE
Query regarding ibm-cos-sdk computeChecksum implementation

### ISSUE THREAD

**Issue by gaskinner84** [IBM/ibm-cos-sdk-python-core#18]
I have used ibm-cos-sdk node package to upload files.

"ibm-cos-sdk": "^1.12.2"

This is how we are initializing ibm cos sdk. Here we do have option to enable computeChecksums.

import { S3 } from 'ibm-cos-sdk';

S3({
endpoint: '"',
apiKeyId: '',
serviceInstanceId: '',
computeChecksums: true
})

We are not sure where the computed check sum is stored and how we can access it.

Please provide the information on how to access calculated checksum for the uploaded object.

KA
Kumar A
Additional comments•2023-01-30 08:25:293h ago
Hi Jiang Lu,

In the below example computeChecksums set it to false.

import { S3 } from 'ibm-cos-sdk';

S3({
endpoint: '"',
apiKeyId: '',
serviceInstanceId: '',
computeChecksums: false
});

To upload file using node js ibm-cos-sdk

cos.upload({
Bucket: BUCKET_NAME,
Key: "TEST.PDF",
Body: req,
ContentMD5: md5Hash
});

Could you provide me the steps how ContentMD5 will be validated in the ibm cos.

Thank you.

Regards,

Gary S.
ACS-Storage Support Lead
IBM Cloud Support

**Comment by gridhawk** [comment]
case was closed by customer. this issue can be closed accordingly
