### ISSUE TITLE
ImportError on DEFAULT_CIPHERS with urllib3>=2.0.0

### ISSUE THREAD

**Issue by mriedem** [IBM/ibm-cos-sdk-python-core#19]
>ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/travis/virtualenv/python3.9.0/lib/python3.9/site-packages/urllib3/util/ssl_.py)

This is with urllib3 2.0.2. DEFAULT_CIPHERS was removed:

https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#200-2023-04-26

Hitting this by pulling in latest `ibm-cos-sdk`.

**Comment by mriedem** [comment]
The requirements here are likely part of the problem:

https://github.com/IBM/ibm-cos-sdk-python-core/blob/2.13.0/setup.py#L9-L10

requests 2.30 adds support for and requires urllib3 2.0.x: https://pyup.io/packages/pypi/requests/changelog?page=1&#2.30.0

So, you can cap requests at `<2.30` until this is fixed, or add support for urllib3 >= 2.0.0 where DEFAULT_CIPHERS is removed.

**Comment by mriedem** [comment]
>requests 2.30 adds support for and requires urllib3 2.0.x

Nevermind it's not a hard requirement on urllib3 2.0.0.

**Comment by zichd** [comment]
There is a vulnerability in Requests <2.31.0
https://github.com/advisories/GHSA-j8r2-6x86-q33q

I can't update to this version because of the urllib3 version requirements collision with ibm-cos-sdk mentioned by @mriedem . Any chance of getting this resolved? Thanks!

**Comment by avinash1IBM** [comment]
@zichd we are working on the above vulnerability and soon you can expect a newer release of ibm-cos-sdk

**Comment by zichd** [comment]
@avinash1IBM Thank you for the good news!

**Comment by avinash1IBM** [comment]
A new version is released to fix this vulnerability. So closing it as resolved.
