### ISSUE TITLE
Maintenance required

### ISSUE THREAD

**Issue by enavarre-ibm** [IBM/ibm-cos-sdk-python-core#22]
The library is becoming obsolete and is incompatible with the IBM client library ecosystem.

#15 41.01 The conflict is caused by:
#15 41.01     ibm-watson-machine-learning 1.0.340 depends on urllib3
#15 41.01     ibm-cloud-sdk-core 3.18.2 depends on urllib3<3.0.0 and >=2.1.0
#15 41.01     ibm-cos-sdk-core 2.12.0 depends on urllib3<1.27 and >=1.26.9

**Comment by avinash1IBM** [comment]
@enavarre-ibm We are working on this to upgrade the urllib3. Also the above issue you mentioned has nothing to do with the incompatibility issue that you mentioned.

**Comment by avinash1IBM** [comment]
@enavarre-ibm The incompatibility issue is fixed in the latest version. Please check and close this issue

**Comment by avinash1IBM** [comment]
Closing this as resolved
