### ISSUE TITLE
Enable tests for python 3.12

### ISSUE THREAD

**Issue by toabctl** [IBM/ibm-cos-sdk-python-core#26]
Ubuntu 24.04 got released recently (in 2024-04) and it contains python 3.12 as default python version. So please enable tests for that python version to make sure the IBM SDK works.

**Comment by IBM-Deeksha** [comment]
We have opened an internal ticket and will get back to you. Thank you for your feedback/request.

**Comment by IBMalok** [comment]
Already we are supporting Python 3.12. Hence closing the ticket.
