### ISSUE TITLE
urllib3 pinned to <1.27 for python versions <3.10

### ISSUE THREAD

**Issue by sreelathasankaranarayanan** [IBM/ibm-cos-sdk-python-core#28]
Is the upper bound required for urllib3 for python versions <3.10, we are having problems with dependency resolution in our project due to this on python version 3.9. Can this upper bound be relaxed? Or is it that the package will not work without this upper bound?

**Comment by avinash1IBM** [comment]
We are working on this and a new version of python will be released soon

**Comment by IBMalok** [comment]
@sreelathasankaranarayanan - Delivered the fixes in 2.13.6. Please verify and close the ticket. Thanks

**Comment by sreelathasankaranarayanan** [comment]
Thank you. Closing the issue as the reported issue is fixed.
