### ISSUE TITLE
Support for python 3.7

### ISSUE THREAD

**Issue by csantanapr** [IBM/ibm-cos-sdk-python-core#3]
I want to include the library in the IBM Cloud Functions using python 3.7
Could you add support for 3.7 or are there any issues already known with python 3.7.

If not could you update the list here: 
https://github.com/IBM/ibm-cos-sdk-python-core/blob/master/setup.py#L61
and release new version

**Comment by cpcunningham** [comment]
Hi @csantanapr I will take a look and get back to you...

**Comment by csantanapr** [comment]
Thanks @cpcunningham 👍

**Comment by cpcunningham** [comment]
hi @csantanapr  - There is a monthly release scheduled for the 12th October that will support python 3.7

**Comment by csantanapr** [comment]
Great

**Comment by csantanapr** [comment]
Current version work with 3.7 or their known issues ? It’s just that the setup.py will be updated ?

**Comment by cpcunningham** [comment]
Current version should work - its just a matter of updatring the setup.py
