### ISSUE TITLE
Why request dependency pinned to <=2.18.4

### ISSUE THREAD

**Issue by csantanapr** [IBM/ibm-cos-sdk-python-core#4]
the request library is already at 2.19.1 https://pypi.org/project/requests/2.19.1/
Why is the library requiring version `<=2.18.4` is there a known problem?
I wan to install latest version `2.19.1` and use this version in IBM Cloud Functions runtime

**Comment by csantanapr** [comment]
installing latest version I get
```
ibm-cos-sdk-core 2.3.0 has requirement requests<=2.18.4,>=2.12.0, but you'll have requests 2.19.1 which is incompatible.
```

**Comment by cpcunningham** [comment]
Hi @csantanapr  - I will take a look....

**Comment by cpcunningham** [comment]
Hi  Barry,

Looking at this fellas queries on github:

1) We would need to use the latest setup.py from aws (includes support 
for 3.7)

2) remove support for python 2.6

3) customise for ibm

Needs to tested against 3.7 and 2.7 but could be put in next weeks patch 
release.

Regards
Connell

**Comment by csantanapr** [comment]
Thanks @cpcunningham 👍

**Comment by cpcunningham** [comment]
hi @csantanapr  - There is a monthly release scheduled for the 12th October that will remove this restriction.
