### ISSUE TITLE
urllib3 version

### ISSUE THREAD

**Issue by gilv** [IBM/ibm-cos-sdk-python-core#5]
Is there particular reason for urllib3>=1.20,<1.24 ?

Current urrlib3 version is 1.24.1, some project uses the latest version of urrlib3,
This make conflicts like

error: urllib3 1.24.1 is installed but urllib3<1.24,>=1.20 is required by {'ibm-cos-sdk-core'}

**Comment by cpcunningham** [comment]
In release 2.4.1 ---- setup.cfg
    urllib3>=1.20,<1.25; python_version=="2.7"
    urllib3>=1.20,<1.25; python_version>="3.4"

This is same as aws - setup.cfg
