### ISSUE TITLE
Is requests version pin still required?

### ISSUE THREAD

**Issue by cletomartin** [IBM/ibm-cos-sdk-python-core#9]
Hi!

We are having some problems with using `ibm-cos-sdk-python-core` in some projects that are using other libraries that depends on `requests`. I think it is due to the current version pinning: https://github.com/IBM/ibm-cos-sdk-python-core/commit/c148e85b05632e0b722252c967611bdf03180ff9#diff-2eeaed663bd0d25b7e608891384b7298R14.

Is this currently required? Seems like it is not at `requirement.txt`: https://github.com/IBM/ibm-cos-sdk-python-core/blob/master/requirements.txt#L11. It would be great the top version could be removed so newer versions of `requests` can be used.

Thanks!

**Comment by mdazam1942** [comment]
I'm having similar issues. The latest version of request is 2.23.0 but setup.py has a declaration that restricts the latest version of request library which is a problem if we use both request and cos sdk in one project. https://github.com/IBM/ibm-cos-sdk-python-core/blob/d129797294d49e47c59aa94a65c985f0b315ee6e/setup.py#L14

**Comment by cletomartin** [comment]
Any update on this?

**Comment by IBMeric** [comment]
Sorry for the late reply and thank you for bringing this to our attention. The version pinning on `requests` is too restrictive. We are updating internally to `<3.0` for the upcoming 2.6.1 patch release. Our internal testing shows no issues, and this aligns with the `requests` team's release process of no breaking changes without increasing the major version number. Feel free to update your local copy until the patch release becomes available.

**Comment by IBMeric** [comment]
Version 2.6.2 is now available (2.6.1 was deprecated). If the problem has been resolved, please close this issue. Thanks!

**Comment by rtveitch** [comment]
Closing this. Let us know if it's still a problem, thanks.
